language: php
php:
- '7'
- '5.6'
- '5.5'
env:
- WP_VERSION=master WP_MULTISITE=0
- WP_VERSION=master WP_MULTISITE=1
- WP_VERSION=4.4
- WP_VERSION=4.4
- WP_VERSION=4.3
matrix:
  allow_failures:
  - env: WP_VERSION=4.3
  - env: WP_VERSION=4.4
  fast_finish: true
before_script:
- export WP_DEVELOP_DIR=/tmp/wordpress/
- mkdir -p $WP_DEVELOP_DIR
- git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
- plugin_slug=$(basename $(pwd))
- plugin_dir=$WP_DEVELOP_DIR/src/wp-content/plugins/$plugin_slug
- cd ..
- mv $plugin_slug $plugin_dir
- cd $WP_DEVELOP_DIR
- echo $WP_DEVELOP_DIR
- cp wp-tests-config-sample.php wp-tests-config.php
- sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
- sed -i "s/yourusernamehere/root/" wp-tests-config.php
- sed -i "s/yourpasswordhere//" wp-tests-config.php
- mysql -e 'CREATE DATABASE wordpress_test;' -uroot
- git clone https://github.com/squizlabs/PHP_CodeSniffer.git php-codesniffer
- git clone https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git
  wordpress-coding-standards
- cd php-codesniffer
- scripts/phpcs --config-set installed_paths ../wordpress-coding-standards
- cd $plugin_dir
- phpenv rehash
script:
- find . \( -name '*.php' \) -exec php -lf {} \;
- "$WP_DEVELOP_DIR/php-codesniffer/scripts/phpcs -p -s -v -n . --standard=./.phpcs.rules.xml
  --extensions=php"
notifications:
  email: false
  slack:
    secure: JgFwx+H9kJunFwUbeRH4CA+q/Hl51afpHmohGrq2nieX9T3lEdDteDiwOH3/IxWItojtLVkGpkCWT8qB8vrqyod5WhZwN2a+9Ei3xyIkR95nOIsRtgBM4LdwDeXe3m7p/CXsVM28aamY5dzaPKieZ3T7b9lp+Bpl0ghrL7jyhH0=
