language: php

php:
  - 7
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1

install:
  - npm install
  - composer install

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - bash .wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - phpunit
  - npm test

notifications:
  email: false
  slack:
    secure: JgFwx+H9kJunFwUbeRH4CA+q/Hl51afpHmohGrq2nieX9T3lEdDteDiwOH3/IxWItojtLVkGpkCWT8qB8vrqyod5WhZwN2a+9Ei3xyIkR95nOIsRtgBM4LdwDeXe3m7p/CXsVM28aamY5dzaPKieZ3T7b9lp+Bpl0ghrL7jyhH0=

